### ISSUE TITLE
Is this still working/supported?

### ISSUE THREAD

**Issue by nitroxplunge** [Jake-Ruston/destiny2#3]
Is this still working/supported? I'm trying to use your API but I keep receiving the error: 
    `[ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer`
but my call to getProfile
    `client.getProfile("PushyParachute4", '1').then(data => console.log(data));`
clearly has it's first argument as a string.

What's going on here? Is this API broken or am I at fault?

**Comment by jacc** [comment]
@nitroxplunge This guy usually abandons projects as soon as he's done with them, but my repo jacc/gamelib will soon have Destiny 2 support in it :)

**Comment by nitroxplunge** [comment]
@jacc Thanks, I will definitely use yours when it's done!

**Comment by Jake-Ruston** [comment]
@nitroxplunge I can't seem to replicate your issue, everything is working fine for me. I changed from strict equality comparison which may resolve it. Could you try again and let me know?

**Comment by Jake-Ruston** [comment]
> @nitroxplunge This guy usually abandons projects as soon as he's done with them, but my repo https://github.com/jacc/gamelib will soon have Destiny 2 support in it :)
> 
> If you'd like to contribute I'd appreciate it!

If I'm done with them what is there to add? :) Also, don't tell people to go to your repo when you have just copied my code from https://github.com/Jake-Ruston/game-data.

**Comment by jacc** [comment]
@Jake-Ruston I'm not copying, just bundling whilst adding more games. I'd love your help, seeing as you are an extremely talented developer. If not, I'm still planning to add you to the README, but I haven't had the time to do it.

**Comment by jacc** [comment]
@Jake-Ruston I added you to the repo. I hope you’ll join.

**Comment by nitroxplunge** [comment]
@Jake-Ruston I seem to have fixed it, I was using the npm package instead of the one here. As for @jacc, I recommenced you give credit to the original creators even if you are just bundling.

**Comment by jacc** [comment]
@Jake-Ruston Of course I will, but I am really hoping that you'll help me:)

**Comment by jacc** [comment]
@Jake-Ruston C'mon man, don't leave me hanging!

**Comment by Jake-Ruston** [comment]
@jacc I just don't see why if you're only refactoring & adding new games to existing code, a new repo had to be made

**Comment by jacc** [comment]
@Jake-Ruston I just figured I'd make a new repo because I tried reaching out to you on your Fornite repo and you didn't reply, as well as the repo (game-data) was 3 months old and my immediate thought was "let me make a new one". Please forgive me and my bad logic, but I could really use your help.
